/**
 * Svelte attachment / action for horizontal scrollable containers.
 * Allows clicking and dragging with a grab cursor to scroll horizontally.
 * When released, smoothly glides with a quintic ease-out animation to fully
 * show the nearest item without any instant jumping or snappy warping.
 */

function findSnapTarget(node: HTMLElement, currentScrollLeft: number, velocity: number): number {
	const children = Array.from(node.children) as HTMLElement[];
	if (!children.length) return currentScrollLeft;

	const parentLeft = node.offsetLeft;
	// Calculate start position of each child relative to container
	const positions = children
		.map((c) => c.offsetLeft - parentLeft)
		.filter((pos) => !isNaN(pos))
		.sort((a, b) => a - b);

	if (!positions.length) return currentScrollLeft;

	const maxScroll = Math.max(0, node.scrollWidth - node.clientWidth);
	if (currentScrollLeft <= 0) return 0;
	if (currentScrollLeft >= maxScroll) return maxScroll;

	// Velocity threshold for flicking (pixels per ms)
	if (velocity < -0.12) {
		// Flicked to scroll forward (right)
		const next = positions.find((p) => p > currentScrollLeft + 15);
		if (next !== undefined) return Math.min(next, maxScroll);
	} else if (velocity > 0.12) {
		// Flicked to scroll backward (left)
		const prev = [...positions].reverse().find((p) => p < currentScrollLeft - 15);
		if (prev !== undefined) return Math.max(0, prev);
	}

	// Gentle release: snap to closest item boundary
	let closest = positions[0];
	let minDiff = Math.abs(positions[0] - currentScrollLeft);

	for (let i = 1; i < positions.length; i++) {
		const diff = Math.abs(positions[i] - currentScrollLeft);
		if (diff < minDiff) {
			minDiff = diff;
			closest = positions[i];
		}
	}

	return Math.min(Math.max(0, closest), maxScroll);
}

export function grabScroll(node: HTMLElement) {
	let isDown = false;
	let isDragging = false;
	let startX = 0;
	let startY = 0;
	let startScrollLeft = 0;
	let lastX = 0;
	let lastTime = 0;
	let velocity = 0;
	let animId: number | null = null;

	node.classList.add('grab-scroll');

	function stopAnimation() {
		if (animId !== null) {
			cancelAnimationFrame(animId);
			animId = null;
		}
	}

	function smoothAnimate(targetLeft: number, duration = 400) {
		stopAnimation();
		const startLeft = node.scrollLeft;
		const distance = targetLeft - startLeft;
		if (Math.abs(distance) < 1) return;

		let startTimestamp: number | null = null;

		function step(now: number) {
			if (startTimestamp === null) startTimestamp = now;
			const elapsed = now - startTimestamp;
			const progress = Math.min(elapsed / duration, 1);

			// Quintic ease-out: starts fast, then smoothly and gently decelerates
			const ease = 1 - Math.pow(1 - progress, 5);
			node.scrollLeft = startLeft + distance * ease;

			if (progress < 1) {
				animId = requestAnimationFrame(step);
			} else {
				animId = null;
			}
		}

		animId = requestAnimationFrame(step);
	}

	function onMouseDown(e: MouseEvent) {
		if (e.button !== 0) return;

		const target = e.target as HTMLElement | null;
		if (target?.closest('input, textarea, select')) return;

		// Stop any in-progress smooth animation immediately on new grab
		stopAnimation();

		isDown = true;
		isDragging = false;
		startX = e.clientX;
		startY = e.clientY;
		lastX = e.clientX;
		lastTime = performance.now();
		velocity = 0;
		startScrollLeft = node.scrollLeft;

		window.addEventListener('mousemove', onMouseMove);
		window.addEventListener('mouseup', onMouseUp);
	}

	function onMouseMove(e: MouseEvent) {
		if (!isDown) return;

		const dx = e.clientX - startX;
		const dy = e.clientY - startY;

		if (!isDragging) {
			if (Math.abs(dx) > 6 && Math.abs(dx) > Math.abs(dy)) {
				isDragging = true;
				node.classList.add('is-dragging');
			}
		}

		if (isDragging) {
			e.preventDefault();
			const now = performance.now();
			const dt = now - lastTime;
			if (dt > 0) {
				// Exponential moving average for velocity to handle subtle pauses
				const instantVelocity = (e.clientX - lastX) / dt;
				velocity = velocity * 0.4 + instantVelocity * 0.6;
			}
			lastX = e.clientX;
			lastTime = now;

			node.scrollLeft = startScrollLeft - dx;
		}
	}

	function onMouseUp() {
		window.removeEventListener('mousemove', onMouseMove);
		window.removeEventListener('mouseup', onMouseUp);

		if (!isDown) return;
		isDown = false;

		if (isDragging) {
			isDragging = false;
			node.classList.remove('is-dragging');

			// Intercept and swallow the click event generated by mouseup
			const preventClick = (clickEvent: MouseEvent) => {
				clickEvent.preventDefault();
				clickEvent.stopPropagation();
				clickEvent.stopImmediatePropagation();
			};

			window.addEventListener('click', preventClick, { capture: true, once: true });
			setTimeout(() => {
				window.removeEventListener('click', preventClick, { capture: true });
			}, 100);

			// Calculate smooth transition target to snap to fully show the item
			const targetLeft = findSnapTarget(node, node.scrollLeft, velocity);

			// Smooth glide to the item without any sudden jump or warp
			smoothAnimate(targetLeft, 450);
		}
	}

	function onDragStart(e: DragEvent) {
		if (isDown) {
			const dx = Math.abs(e.clientX - startX);
			const dy = Math.abs(e.clientY - startY);
			if (dx >= dy || isDragging) {
				e.preventDefault();
			}
		}
	}

	node.addEventListener('mousedown', onMouseDown);
	node.addEventListener('dragstart', onDragStart);

	return () => {
		stopAnimation();
		node.classList.remove('grab-scroll', 'is-dragging');
		node.removeEventListener('mousedown', onMouseDown);
		node.removeEventListener('dragstart', onDragStart);
		window.removeEventListener('mousemove', onMouseMove);
		window.removeEventListener('mouseup', onMouseUp);
	};
}
