import type { Component } from 'svelte';
import {
	Plus,
	TriangleAlert,
	CircleAlert,
	ChevronDown,
	ArrowDownWideNarrow,
	ArrowLeft,
	ArrowRight,
	RotateCcw,
	Undo2,
	ChevronUp,
	ArrowUp,
	ArrowUpDown,
	ArrowUpNarrowWide,
	AudioWaveform,
	BookmarkPlus,
	BookmarkCheck,
	BookmarkMinus,
	BookPlus,
	Video,
	VideoOff,
	X,
	CircleX,
	Disc,
	CircleCheck,
	Clock,
	CloudSync,
	CloudUpload,
	Coffee,
	Pipette,
	Copy,
	Crown,
	LayoutDashboard,
	Database,
	Trash,
	GripVertical,
	HardDrive,
	Pencil,
	ArrowLeftRight,
	FastForward,
	Heart,
	RotateCcwClock,
	House,
	WifiOff,
	ImagePlus,
	Infinity as InfinityIconLucide,
	Info,
	Keyboard,
	Library,
	Link,
	LoaderCircle,
	LogOut,
	Maximize2,
	Maximize,
	Mic,
	MicVocal,
	Minimize2,
	Minimize,
	Minus,
	Moon,
	Sun,
	Ellipsis,
	EllipsisVertical,
	Music,
	Music2,
	SkipForward,
	SkipBack,
	PictureInPicture2,
	Palette,
	Pause,
	Pin,
	PinOff,
	CirclePlay,
	Play,
	ListMusic,
	ListPlus,
	ListX,
	SlidersHorizontal,
	ListOrdered,
	Radio,
	RefreshCw,
	Repeat,
	Repeat1,
	Save,
	Search,
	FileSearch,
	Settings,
	Share2,
	Shuffle,
	PanelLeftClose,
	PanelLeftOpen,
	Square,
	Layers,
	ThumbsDown,
	ThumbsUp,
	Check,
	ChevronsUpDown,
	UserX,
	CircleUser,
	Users,
	User,
	UserCheck,
	UserMinus,
	UserPlus,
	Eye,
	EyeOff,
	Volume2,
	VolumeX
} from '@lucide/svelte';

export type IconComponent = Component<any>;
export type IconSvgElement = Component<any>;

export {
	Plus as Add01Icon,
	Plus as PlusSignIcon,
	TriangleAlert as Alert02Icon,
	CircleAlert as AlertCircleIcon,
	ChevronDown as ArrowDown01Icon,
	ArrowDownWideNarrow as ArrowDownWideNarrowIcon,
	ArrowLeft as ArrowLeft01Icon,
	ArrowRight as ArrowRight01Icon,
	RotateCcw as ArrowTurnBackwardIcon,
	ChevronUp as ArrowUp01Icon,
	ArrowUp as ArrowUpBigIcon,
	ArrowUpDown as ArrowUpDownIcon,
	ArrowUpDown as Sorting01Icon,
	ArrowUpNarrowWide as ArrowUpNarrowWideIcon,
	AudioWaveform as AudioWave02Icon,
	BookmarkPlus as BookmarkAdd02Icon,
	BookmarkCheck as BookmarkCheck02Icon,
	BookmarkMinus as BookmarkMinus02Icon,
	BookPlus as BookPlusIcon,
	Video as CameraVideoIcon,
	Video as Video01Icon,
	VideoOff as VideoOffIcon,
	X as Cancel01Icon,
	CircleX as Cancel02Icon,
	Disc as CdIcon,
	Disc as Vynil02Icon,
	CircleCheck as CheckmarkCircle01Icon,
	CircleCheck as CheckmarkCircle02Icon,
	CircleCheck as CheckmarkCircle03Icon,
	Clock as Clock01Icon,
	CloudSync as CloudSyncIcon,
	CloudUpload as CloudUploadIcon,
	Coffee as Coffee02Icon,
	Pipette as ColorPickerIcon,
	Copy as Copy01Icon,
	Crown as CrownIcon,
	LayoutDashboard as DashboardSquare02Icon,
	Database as Database02Icon,
	Trash as Delete02Icon,
	GripVertical as DragDropHorizontalIcon,
	HardDrive as DriveIcon,
	Pencil as Edit01Icon,
	Pencil as PencilEdit02Icon,
	ArrowLeftRight as Exchange01Icon,
	FastForward as FastForwardIcon,
	Heart as FavouriteIcon,
	RotateCcwClock as HistoryIcon,
	House as Home01Icon,
	WifiOff as HotspotOfflineIcon,
	ImagePlus as ImageAdd02Icon,
	InfinityIconLucide as InfinityIcon,
	Info as InformationCircleIcon,
	Keyboard as KeyboardIcon,
	Library as LibraryIcon,
	Link as Link04Icon,
	RotateCcw as ListRestartIcon,
	LoaderCircle as Loading03Icon,
	LogOut as Logout01Icon,
	Maximize2 as Maximize01Icon,
	Maximize as MaximizeScreenIcon,
	MicVocal as Mic01Icon,
	MicVocal as MicVocalIcon,
	Mic as MicIcon,
	Minimize2 as Minimize01Icon,
	Minimize as MinimizeScreenIcon,
	Minus as MinusSignIcon,
	Moon as Moon02Icon,
	Sun as Sun01Icon,
	Ellipsis as MoreHorizontalIcon,
	EllipsisVertical as MoreVerticalIcon,
	Music as MusicNote01Icon,
	Music2 as MusicNoteSquare02Icon,
	SkipForward as NextIcon,
	SkipBack as PreviousIcon,
	PictureInPicture2 as PictureInPictureIcon,
	Palette as PaintBoardIcon,
	Pause as PauseIcon,
	Pin as PinIcon,
	PinOff as PinOffIcon,
	CirclePlay as PlayCircleIcon,
	Play as PlayIcon,
	ListMusic as Playlist02Icon,
	ListMusic as PlayListIcon,
	ListPlus as PlayListAddIcon,
	ListX as PlayListRemoveIcon,
	SlidersHorizontal as PreferenceVerticalIcon,
	ListOrdered as Queue01Icon,
	Radio as Radio02Icon,
	RefreshCw as RefreshIcon,
	Repeat as RepeatIcon,
	Repeat1 as RepeatOne01Icon,
	Save as SaveIcon,
	Search as Search01Icon,
	Search as SearchIcon,
	FileSearch as SearchList01Icon,
	Settings as Settings01Icon,
	Settings as Settings02Icon,
	Share2 as Share08Icon,
	Shuffle as ShuffleIcon,
	PanelLeftClose as SquareArrowLeft01Icon,
	PanelLeftOpen as SquareArrowRight01Icon,
	Square as SquareIcon,
	Layers as SquareStackIcon,
	ThumbsDown as ThumbsDownIcon,
	ThumbsUp as ThumbsUpIcon,
	Check as Tick02Icon,
	ChevronsUpDown as UnfoldMoreIcon,
	UserX as UserBlock01Icon,
	CircleUser as UserCircleIcon,
	Users as UserGroup02Icon,
	Users as UserListIcon,
	Users as UserMultiple02Icon,
	User as UserIcon,
	UserCheck as UserLove02Icon,
	UserCheck as UserStar01Icon,
	UserMinus as UserMinus01Icon,
	UserMinus as UserRemove01Icon,
	UserPlus as UserSharingIcon,
	Eye as ViewIcon,
	EyeOff as ViewOffSlashIcon,
	Volume2 as VolumeHighIcon,
	VolumeX as VolumeMute02Icon
};

export {
	House as Home,
	RotateCcwClock as History,
	Trash as Trash2
};

export * from '@lucide/svelte';
export { default as Icon } from '$lib/components/Icon.svelte';
export { default as HugeiconsIcon } from '$lib/components/Icon.svelte';
